import Navbar from "@/components/navbar";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Band Wagon | Artist Profile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className=" min-h-screen bg-black">
      <Navbar />
      <div className=" flex gap-4 h-full bg-black ">
        <div className=" basis-[25%] border-r"></div>
        <div className=" grow p-16">{children}</div>
      </div>
    </div>
  );
}
